name: Periodic Ping

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the URL
        uses: actions/github-script@v7
        with:
          script: |
            const response = await fetch(process.env.PING_URL);
            console.log(`Pinged ${process.env.PING_URL} with status ${response.status}`);
        env:
          PING_URL: ${{ secrets.PING_URL }}
