name: Periodic Ping Monitor

env:
  DEFAULT_WORKFLOW_ID: 'ping.yml'
  DEFAULT_CHECK_INTERVAL: '5'

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger
    inputs:
      workflow_id:
        description: 'Workflow id to check and trigger'
        required: false
        default: ${{ env.DEFAULT_WORKFLOW_ID }}
      check_interval:
        description: 'Time interval (in minutes)'
        required: false
        default: ${{ env.DEFAULT_CHECK_INTERVAL }}

jobs:
  workflow-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Workflow Check & Trigger
        uses: actions/github-script@v7
        with:
          script: |
            const workflow = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.payload.inputs?.workflow_id || process.env.DEFAULT_WORKFLOW_ID
            };

            // Fetch workflow details
            const workflow_response = await github.rest.actions.getWorkflow(workflow);
            const workflow_name = workflow_response.data.name;

            // Fetch last successful workflow run
            const workflow_runs_response = await github.rest.actions.listWorkflowRuns({
              ...workflow,
              status: 'success',
              per_page: 1
            });
            const last_run_time = new Date(workflow_runs_response.data.workflow_runs[0].created_at);
            
            const time_since_last_run = new Date() - last_run_time;
            const check_interval = parseInt(context.payload.inputs?.check_interval || process.env.DEFAULT_CHECK_INTERVAL) * 60 * 1000;  // Convert minutes to milliseconds

            if (time_since_last_run >= check_interval) {
              console.log(`The workflow "${workflow_name}" has missed its schedule.`);
              // Run workflow
              await github.rest.actions.createWorkflowDispatch({
                ...workflow,
                ref: context.ref
              });
            } else {
              console.log(`The workflow "${workflow_name}" is on schedule.`);
            }
