name: Periodic Ping

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2    # Prevent hung jobs
    steps:
      - name: Ping the URL
        id: ping
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" \
            --connect-timeout 10 \
            --max-time 30 \
            --retry 3 \
            --retry-delay 10 \
            --retry-max-time 90 \
            --retry-all-errors \
            ${{ secrets.PING_URL }})
          
          if [ "$status_code" -ge 200 ] && [ "$status_code" -lt 300 ]; then
            echo "✅ Success with status code: $status_code"
            exit 0
          else
            echo "::error::Failed with status code: $status_code"
            echo "::warning::Last attempt failed after 3 retries"
            exit 1
          fi
