name: Periodic Ping Monitor

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger
    inputs:
      workflow_id:
        description: 'The workflow id to check and trigger'
        required: false
        default: 'ping.yml'  # Default workflow ID

jobs:
  check-ping-timeliness:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Trigger Periodic Ping
        uses: actions/github-script@v6
        with:
          script: |
            const workflowDetails = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: ${{ inputs.workflow_id }}
            };
            const response = await github.rest.actions.listWorkflowRuns({
              ...workflowDetails,
              status: 'completed',
              per_page: 5
            });
            const lastRunTime = new Date(response.data.workflow_runs[0].created_at);
            const expectedInterval = 10 * 60 * 1000;  // 10 minutes in milliseconds
            const diff = new Date() - lastRunTime;

            if (diff > expectedInterval) {
              console.log(`The workflow has missed its schedule.`);
              await github.rest.actions.createWorkflowDispatch({
                ...workflowDetails,
                ref: context.ref
              });
            } else {
              console.log(`The workflow is on schedule.`);
            }
