name: Periodic Ping

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:         # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Ping the URL
        uses: actions/github-script@v6
        with:
          script: |
            const response = await fetch(process.env.PING_URL);
            console.log(`Pinged ${process.env.PING_URL} with status ${response.status}`);
        env:
          PING_URL: ${{ secrets.PING_URL }}
