name: Periodic Ping Monitor

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger
    inputs:
      workflow_id:
        description: 'The workflow id to check and trigger'
        required: false
        default: 'ping.yml'  # Default workflow ID

jobs:
  check-ping-timeliness:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Trigger Periodic Ping
        uses: actions/github-script@v6
        with:
          script: |
            const workflow = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.payload.inputs.workflow_id
            };

            // Fetch workflow details
            const workflowResponse = await github.rest.actions.getWorkflow(workflow);
            const workflowName = workflowResponse.data.name;

            // Fetch last successful workflow run
            const workflowRunsResponse = await github.rest.actions.listWorkflowRuns({
              ...workflow,
              status: 'success',
              per_page: 1
            });
            const lastRunTime = new Date(workflowRunsResponse.data.workflow_runs[0].created_at);
            
            const timeSinceLastRun = new Date() - lastRunTime;
            const checkInterval = 10 * 60 * 1000;  // 10 minutes in milliseconds

            if (timeSinceLastRun >= checkInterval) {
              console.log(`The workflow "${workflowName}" has missed its schedule.`);
              // Run workflow
              await github.rest.actions.createWorkflowDispatch({
                ...workflow,
                ref: context.ref
              });
            } else {
              console.log(`The workflow "${workflowName}" is on schedule.`);
            }
