name: Periodic Ping Monitor

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  check-ping-timeliness:
    runs-on: ubuntu-latest

    steps:
      - name: Check and Trigger Periodic Ping
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ping.yml',
              status: 'completed',
              per_page: 5
            });
            const lastRunTime = new Date(response.data.workflow_runs[0].created_at);
            const expectedInterval = 10 * 60 * 1000;  // 10 minutes in milliseconds
            const diff = new Date() - lastRunTime;

            if (diff > expectedInterval) {
              console.log("The Periodic Ping workflow has missed its schedule.");
            } else {
              console.log("The Periodic Ping workflow is on schedule.");
            }
